name:                terminal
synopsis:            Portable terminal interaction library
version:             0.1.0.0
github:              "lpeterse/terminal"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/terminal#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- async
- stm
- mtl
- transformers

library:
  ghc-options: -Werror
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        cpp-options: -DWINDOWS
        dependencies:
        - Win32
      else:
        build-tools:
        - hsc2hs
        dependencies:
        - unix

executables:
  terminal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal

tests:
  terminal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
