name:                terminal
synopsis:            Portable terminal interaction library
version:             0.1.0.0
github:              "lpeterse/terminal"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/terminal#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- exceptions
- stm
- text
- transformers

library:
  ghc-options: -Werror
  exposed-modules:
    - System.Terminal
    - System.Terminal.Color
    - System.Terminal.Events
    - System.Terminal.Modes
    - System.Terminal.Pretty
  other-modules:
    - System.Terminal.Platform
    - System.Terminal.Class
    - System.Terminal.AnsiTerminalT
  source-dirs: src
  when:
    - condition: os(windows)
      then:
        cpp-options: -DWINDOWS
        include-dirs:
          - platform/windows/include
        source-dirs:
          - platform/windows/src
        c-sources:
          - platform/windows/cbits/hs_terminal.c
        dependencies:
          - Win32
      else:
        source-dirs:
          - platform/posix/src
        dependencies:
          - unix

executables:
  terminal-cli:
    main:                Main.hs
    source-dirs:         terminal-cli
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
  terminal-out:
    main:                Main.hs
    source-dirs:         terminal-out
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal

tests:
  terminal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
